<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class TourGuideSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (env('DB_CONNECTION') == 'mysql') {
            \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        }
        DB::table('tour_guides')->truncate();
        DB::table('tour_guides')->insert([
            [
                'id' => 1,
                'account_id' => 5,
                'full_name' => 'Mai Quang Hiếu',
                'year_of_birth' => 1998,
                'gender' => 1,
                'price' => 1000000,
                'phone' => '0979691998',
                'email' => 'maiquanghieu6998@gmail.com',
                'description' => 'Tôi là một hướng dẫn viên yêu thích sự tự do. . Tôi sẽ kể bạn nghe rất nhiêu huyền thoại về nơi đây và bạn sẽ bất ngờ đó.',
                'avatar' => 'mai-quang-hieu_mlltkf',
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'account_id' => 6,
                'full_name' => 'Phạm Quang Trường',
                'year_of_birth' => 1996,
                'gender' => 1,
                'price' => '800000',
                'phone' => '0912577620',
                'email' => 'dothaianh06@gmail.com',
                'description' => 'Là một người trầm lặng, co thể nhiều khách hàng sẽ không thích điều đó ửo một hướng dẫn viên. Tôi có xe riêng, tôi sẽ đưa bạn đến bất cứ nơi đâu trong phạm vị tham quan ma bạn muốn, miễn phí.
                Câu nói yêu thích:"Hạnh phúc đến từ từng hơi thở"',
                'avatar' => 'pham-quang-truong_wb2lgh',
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'account_id' => 7,
                'full_name' => 'Đặng Quang Chính',
                'year_of_birth' => 1996,
                'gender' => 1,
                'price' => 1000000,
                'phone' => '0912511440',
                'email' => 'clonen89@gmail.com',
                'description' => 'Bạn mới đến nơi đây, và bạn tò mò về những món đặc sản của vùng. Đừng lo lắng gì cả, vì mọi người gọi tôi là "hướng dẫn ẩm thực".Tất nhiên, với vai trò là hướng dẫn viên của bạn, tôi sẽ giúp bạn khám phá tối đa những gì nên biết về vùng đất mà đôi chân bạn đang đưa bạn đi',
                'avatar' => 'dang-quang-chinh_k3fnkv',
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'account_id' => 8,
                'full_name' => 'Nguyễn Hồng Nhung',
                'year_of_birth' => 1994,
                'gender' => 2,
                'price' => 2000000,
                'phone' => '0347513690',
                'email' => 'c38772740@gmail.com',
                'description' => 'Tôi đã dẫn tour 5 năm, tôi hiểu rõ bạn, là khách hàng của tôi cần gì và mong muốn gì. Tất nhiên, chỉ cần bạn yêu cầu, trong khả năng của tôi, tôi sẽ đáp ứng để bạn có trải nghiệm chuyến đi tuyệt vời. Hãy đi cùng tôi để hiểu mẹ Việt Nam đẹp thế nào
                Câu nói yêu thích:"Nhà là nơi mà con đang đứng, nhớ về người thân và  con sẽ thấy an toàn"',
                'avatar' => 'nguyen-hong-nhung_r4vzey',
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'status' => 2,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'account_id' => 9,
                'full_name' => 'Phạm Thị Hoa',
                'year_of_birth' => 1992,
                'gender' => 2,
                'price' => 800000,
                'phone' => '0347866439',
                'email' => 'nickclone043@gmail.com',
                'description' => 'Chào mừng bạn đến với Bắc Ninh. Bạn muốn đến hội Lim khi không biết gì và muốn tìm hiểu ư? Đã có tôi ở đây rồi, tôi sẽ dẫn bạn đi tham quan nét đẹp văn hoá đã được tổ chứ văn hoá thế giới công nhận.
                Câu nói yêu thích:"Tôi sống như đoá hoa này, toả ngát hương thơm cho đời"',
                'avatar' => 'pham-thi-hoa_ebf0m7',
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'account_id' => 10,
                'full_name' => 'Nguyễn Thị Vân Anh',
                'year_of_birth' => 1996,
                'gender' => 2,
                'price' => 1500000,
                'phone' => '0979544726',
                'email' => 'n38243370@gmail.com',
                'description' => 'Bạn muốn dẫn người bạn nước ngoài mà mình mới quen đi tham quan nhưng không biết rõ lịch sử và các địa danh? Với 2 năm kinh nghiệm dẫn tour, có thể nói được 3 ngoại ngữ là tiếng Anh, tiếng Đức, tiếng Trung. Hãy đến với tôi và cùng nhau tìm hiểu, khám phá Việt Nam nào',
                'avatar' => 'nguyen-thi-van-anh_nbgtuu',
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'account_id' => 11,
                'full_name' => 'Phạm Minh Hiếu',
                'year_of_birth' => 1995,
                'gender' => 1,
                'price' => '1000000',
                'phone' => '0905422944',
                'email' => 'nickclone450@gmail.com',
                'description' => 'Bạn bè luôn nhận xét tôi là người năng nổ nhiệt tình. Tôi cũng sẽ nói điều đó, nhiều năm dẫn tour kết hợp tổ chức teambuilding, tôi biết làm thế nào để khuấy động không khí, để kết nối mọi người. Bạn có một nhóm bạn nhiều người, muốn tìm một nơi để tham quan và vui chơi?  Hãy tin tưởng tôi.',
                'avatar' => 'pham-minh-hieu_daftwk',
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'account_id' => 12,
                'full_name' => 'Phạm Châu Anh',
                'year_of_birth' => 1996,
                'gender' => 2,
                'price' => '1200000',
                'phone' => '0949511230',
                'email' => 'nickc8767@gmail.com',
                'description' => 'Tôi biết rằng bạn có nhiều người bạn là người nước ngoài.Hãy tin tưởng ở tôi, tôi có thể nói 4 ngoại ngữ: Anh, Pháp, Nhật, Hàn',
                'avatar' => 'Phạm-châu-anh_qleink',
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'account_id' => 13,
                'full_name' => 'Nguyễn Quỳnh Vân',
                'year_of_birth' => 1997,
                'gender' => 2,
                'price' => 800000,
                'phone' => '0849997778',
                'email' => 'nickclone646@gmail.com',
                'avatar' => 'nguyễn-quỳnh-vân_nadthr',
                'description' => 'Đến thăm quan thủ đô nhưng không nắm rõ kiến thức về nơi đây? Tôi ở đây để giúp bạn, tôi sẽ đưa bạn đi qua 36 phố phường nổi tiếng, ngắm nhìn hồ gươm và quảng trường Ba Đình huyền thoại.. Hãy đến với tôi, tôi có thể nói được tiếng Anh nên hãy dẫn theo một người bạn nữa nhé',
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'account_id' => 14,
                'full_name' => 'Trần Tiến Dụng',
                'year_of_birth' => 2001,
                'gender' => 1,
                'price' => 500000,
                'phone' => '0969121250',
                'email' => 'nclone42@gmail.com',
                'avatar' => 'Trần-tiến-dụng_lqqd7y',
                'description' => 'Đến nơi đây nhưng chưa biết phải tìm hiểu những gì ư? Hãy tìm đến tôi, giá cả thật phải chăng! tôi cũng có thể nói tiếng Anh, hãy giới thiệu người bạn nước ngoài của bạn đi cùng, hãy đi cùng tôi, tôi sẽ giơi thiệu Việt Nam cho họ cũng như cho bạn thấy một cái nhìn sâu hơn về quê hương của mình',
                'card' => false,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],

        ]);
        if (env('DB_CONNECTION') == 'mysql') {
            \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 1');
        }
    }
}
