<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class TourGuideSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('admins')->truncate();
        DB::table('admins')->insert([
            [
                'id' => 1,
                'account_id' => 5,
                'full_name' => 'Mai Quang Hiếu',
                'age' => '23',
                'price' => 1000000,
                'phone' => '0979691998',
                'email' => 'maiquanghieu6998@gmail.com',
                'description' => 'Tự tin, thân thiện, vui vẻ. Có thể dẫn tour bằng tiếng Anh',
                'thumbnail' => '',
                'area_id' => '1',
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'account_id' => 6,
                'full_name' => 'Phạm Quang Trường',
                'age' => '24',
                'price' => '800000',
                'phone' => '0912577620',
                'email' => 'truongpham97@gmail.com',
                'description' => 'trầm lắng, thích đọc sách và tìm hiểu nhiều nền văn hoá cũng như lịch sử',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'account_id' => 7,
                'full_name' => 'Đặng Quang Chính',
                'age' => '24',
                'price' => 1000000,
                'phone' => '0912511440',
                'email' => 'chinhdangquang777@gmail.com',
                'description' => 'Năng nổ, hiểu biết nhiều về ẩm thực',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => '',
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'account_id' => 8,
                'full_name' => 'Nguyễn Hồng Nhung',
                'age' => '26',
                'price' => 2000000,
                'phone' => '0347513690',
                'email' => 'nhungnguyen494@gmail.com',
                'description' => '5 năm kinh nghiệm dẫn tour',
                'thumbnail' => '',
                'area_id' => 32,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 2,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'account_id' => 9,
                'full_name' => 'Phạm Thị Hoa',
                'age' => '38',
                'price' => 800000,
                'phone' => '0347866439',
                'email' => 'phamhoathi_tourguider@gmail.com',
                'description' => 'Chuyên dẫn đoàn xem hội Lim, có thể hát quan họ',
                'thumbnail' => '',
                'area_id' => 4,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'account_id' => 10,
                'full_name' => 'Nguyễn Thị Vân Anh',
                'age' => '24',
                'price' => 1500000,
                'phone' => '0979544726',
                'email' => 'vivianng@gmail.com',
                'description' => 'Là người vui vẻ. Có thể dẫn tour người nước ngoài với tiếng Anh và tiếng Pháp',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'account_id' => 11,
                'full_name' => 'Phạm Minh Hiếu',
                'age' => '25',
                'price' => '1000000',
                'phone' => '0905422944',
                'email' => 'hieu_pham_95@gmail.com',
                'description' => 'là người năng nổ, nhiệt tình. Có nhiều kinh nghiệm dẫn đoàn công ty tổ chức team building',
                'thumbnail' => '',
                'area_id' => 25,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'account_id' => 12,
                'full_name' => 'Phạm Châu Anh',
                'age' => '24',
                'price' => '1200000',
                'phone' => '0949511230',
                'email' => 'chauanhanh@gmail.com',
                'description' => 'Tự tin, chuyên dẫn tour người nước ngoài với tiếng Anh, Đức, Pháp',
                'thumbnail' => '',
                'area_id' => 25,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'account_id' => 13,
                'full_name' => 'Nguyễn Quỳnh Vân',
                'age' => '23',
                'price' => 800000,
                'phone' => '0849997778',
                'email' => 'quingvian98@gmail.com',
                'thumbnail' => '',
                'description' => 'Dẫn tour Hà Nội, thế mạnh là tiếng Anh',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'account_id' => 14,
                'full_name' => 'Trần Tiến Dụng',
                'age' => '19',
                'price' => 500000,
                'phone' => '0969121250',
                'email' => 'dungtt_tg@gmail.com',
                'thumbnail' => '',
                'description' => 'Hướng dẫn viên địa phương. Có thể nói tiếng Anh ',
                'area_id' => 18,
                'card' => false,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'account_id' => 15,
                'full_name' => 'Đặng Tiến ',
                'age' => '22',
                'price' => 12000000,
                'phone' => '09125561440',
                'email' => 'tieneastern99@gmail.com',
                'description' => 'Năng nổ, hiểu biết nhiều về ẩm thực. Dẫn tour Tam Đảp',
                'thumbnail' => '',
                'area_id' => 3,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'account_id' => 16,
                'full_name' => 'Phạm Quang Hưng',
                'age' => '25',
                'price' => 1000000,
                'phone' => '0342517940',
                'email' => 'hungpham967@gmail.com',
                'description' => 'Chuyên tổ dẫn tour công ty tổ chức teambuilding khu vực Tam Đảo',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'account_id' => 17,
                'full_name' => 'Đỗ Thanh Hùng',
                'age' => '36',
                'price' => 1500000,
                'phone' => '0322581240',
                'email' => 'thanhhungdo8x@gmail.com',
                'description' => 'Năng nổ, hiểu biết nhiều về lịch sử. Dẫn tour tham quan di tích Điện Biên phủ',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'account_id' => 18,
                'full_name' => 'Hoàng Minh Thái',
                'age' => '27',
                'price' => 1000000,
                'phone' => '097251240',
                'email' => 'hoangthaihp@gmail.com',
                'description' => 'chuyên tổ chức sự kiện, team building khu vực Đồ Sơn',
                'thumbnail' => '',
                'area_id' => 8,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'account_id' => 19,
                'full_name' => 'Mai Tiến Hưng',
                'age' => '28',
                'price' => 1000000,
                'phone' => '0983703040',
                'email' => 'tomorrowhung9x@gmail.com',
                'description' => 'Dẫn tour cố đô Hoa Lư',
                'thumbnail' => '',
                'area_id' => 11,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'account_id' => 20,
                'full_name' => 'Đặng Thị Kiều Chinh',
                'age' => '24',
                'price' => 1000000,
                'phone' => '0968814151',
                'email' => 'chinhdang_femaletour@gmail.com',
                'description' => 'Dẫn tour tham quan cố đô Hoa ',
                'thumbnail' => '',
                'area_id' => 11,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'account_id' => 21,
                'full_name' => 'Nguyễn Hà Trang',
                'age' => '20',
                'price' => 4000000,
                'phone' => '0964838082',
                'email' => 'changchangng2k@gmail.com',
                'description' => 'Tiếng Anh và tiếng Pháp tự tin giao tiếp. Dẫn tour thành Cổ Loa',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => false,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'account_id' => 22,
                'full_name' => 'Mai Xuân Dũng',
                'age' => '19',
                'price' => 500000,
                'phone' => '0974673727',
                'email' => 'dungMX202@gmail.com',
                'description' => 'Nói tiếng Anh tốt. Dẫn tour tham quan Hà Giang',
                'thumbnail' => '',
                'area_id' => 18,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'account_id' => 23,
                'full_name' => 'Phùng Thanh Hằng',
                'age' => '22',
                'price' => 6000000,
                'phone' => '0978963646',
                'email' => 'phungthanhhung@gmail.com',
                'description' => 'Năng nổ, hiểu biết nhiều về ẩm thực. Dẫn tour địa phương vùng Cao Bằng',
                'thumbnail' => '',
                'area_id' => 19,
                'card' => false,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'account_id' => 24,
                'full_name' => 'Trần Hồng Hiếu',
                'age' => '26',
                'price' => 1000000,
                'phone' => '0964595058',
                'email' => 'tranpinkhieu_guide@gmail.com',
                'description' => 'Tourguide tham quan Thái Nguyên. Biết tiếng Anh và năng động',
                'thumbnail' => '',
                'area_id' => 23,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'account_id' => 25,
                'full_name' => 'Lê Hồng Phong',
                'age' => '24',
                'price' => 8000000,
                'phone' => '0912716449',
                'email' => 'windypinky@gmail.com',
                'description' => 'Mọi người đánh giá là hài hước. Tourguider địa phương',
                'thumbnail' => '',
                'area_id' => 23,
                'card' => false,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'account_id' => 26,
                'full_name' => 'Vũ Hoàng Sơn',
                'age' => '24',
                'price' => 6000000,
                'phone' => '0979926242',
                'email' => 'goldenmoutain_87@gmail.com',
                'description' => 'Tourguider địa phương',
                'thumbnail' => '',
                'area_id' => 27,
                'card' => false,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'account_id' => 27,
                'full_name' => 'Hoàng Thanh Luyến',
                'age' => '25',
                'price' => 1000000,
                'phone' => '0975624292',
                'email' => 'kimluyen_96@gmail.com',
                'description' => 'Tourguider địa phương, dẫn tour tham quan làng Sen. Biết tiếng Anh',
                'thumbnail' => '',
                'area_id' => 28,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'account_id' => 28,
                'full_name' => 'Lưu Văn Khánh',
                'age' => '24',
                'price' => 700000,
                'phone' => '0702159169',
                'email' => 'luuvankhanhht@gmail.com',
                'description' => 'Tourguider địa phương',
                'thumbnail' => '',
                'area_id' => 29,
                'card' => false,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'account_id' => 29,
                'full_name' => 'Hoàng Khánh Kiều Ly',
                'age' => '24',
                'price' => 1000000,
                'phone' => '0777392989',
                'email' => 'kieuly_pinky@gmail.com',
                'description' => 'Tour thành cổ Quảng Trị-Ngã ba Đồng Lộc, nói được Tiếng Anh',
                'thumbnail' => '',
                'area_id' => 31,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'account_id' => 30,
                'full_name' => 'Đặng Văn Tiến',
                'age' => '28',
                'price' => 1200000,
                'phone' => '0913211990',
                'email' => 'dangvantien@gmail.com',
                'description' => 'Dẫn tour Quảng Trị, kiêm MC chương trình teambuilding',
                'thumbnail' => '',
                'area_id' => 31,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'account_id' => 31,
                'full_name' => 'Vũ Văn Phong',
                'age' => '24',
                'price' => 800000,
                'phone' => '0912511440',
                'email' => 'phongvubuffalo@gmail.com',
                'description' => 'Năng nổ, hiểu biết nhiều về kiến thức lịch sử. Giao tiếp và dẫn tour bằng tiếng Anh tốt',
                'thumbnail' => '',
                'area_id' => 31,
                'card' => false,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'account_id' => 32,
                'full_name' => 'Hoàng Khánh Huyền',
                'age' => '28',
                'price' => 2000000,
                'phone' => '0788240808',
                'email' => 'khanhhuy_windy@gmail.com',
                'description' => 'Tourguider các di tích ở Huế. Sử dụng tốt tiếng Anh và tiếng Hàn',
                'thumbnail' => '',
                'area_id' => 32,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'account_id' => 33,
                'full_name' => 'Phùng Thanh Độ ',
                'age' => '30',
                'price' => 1500000,
                'phone' => '0795093909',
                'email' => 'mixitourguide@gmail.com',
                'description' => 'Hài hước vui tính. Dẫn tour Huế, Hội An',
                'thumbnail' => '',
                'area_id' => 33,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'account_id' => 34,
                'full_name' => 'Hà Văn Tiến',
                'age' => '29',
                'price' => 1200000,
                'phone' => '0979511288',
                'email' => 'Tienguider_90@gmail.com',
                'description' => 'Dẫn tour Đà Nẵng, Hội An. Có thể kiêm cả MC',
                'thumbnail' => '',
                'area_id' => 33,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'account_id' => 35,
                'full_name' => 'Trần Kiều Ninh',
                'age' => '26',
                'price' => 1000000,
                'phone' => '0912534267',
                'email' => 'ninhtran_95@gmail.com',
                'description' => 'Dẫn tour Đà Nẵng - Hội An. Sử dụng tiếng Hàn tốt',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'account_id' => 36,
                'full_name' => 'Lê Quang Huy',
                'age' => '23',
                'price' => 400000,
                'phone' => '0901775929',
                'email' => 'quanghuy_tommy@gmail.com',
                'description' => 'Tourguider địa phương ở Bình Định',
                'thumbnail' => '',
                'area_id' => 35,
                'card' => false,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'account_id' => 37,
                'full_name' => 'Trần Trung Hải',
                'age' => '34',
                'price' => 800000,
                'phone' => '0902234992',
                'email' => 'middlesea_XX@gmail.com',
                'description' => 'Teambuilding Nha Trang',
                'thumbnail' => '',
                'area_id' => 38,
                'card' => false,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 38,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'account_id' => 38,
                'full_name' => 'Nguyễn Ngọc Hương',
                'age' => '24',
                'price' => 800000,
                'phone' => '0904566229',
                'email' => 'ngocperfume777@gmail.com',
                'description' => 'Teambuilding Nha Trang',
                'thumbnail' => '',
                'area_id' => 38,
                'card' => false,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'account_id' => 39,
                'full_name' => 'Mai Hồng Đức',
                'age' => '24',
                'price' => 800000,
                'phone' => '0906255229',
                'email' => 'hongduc_998@gmail.com',
                'description' => 'Tourguider Quy Nhơn',
                'thumbnail' => '',
                'area_id' => 40,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'account_id' => 40,
                'full_name' => 'Lê Quang Dương',
                'age' => '23',
                'price' => 1000000,
                'phone' => '0936143173',
                'email' => 'quangduong_97@gmail.com',
                'description' => 'Tourguider Quy Nhơn',
                'thumbnail' => '',
                'area_id' => 40,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'account_id' => 41,
                'full_name' => 'Mạc Văn Hoàng Hưng',
                'age' => '32',
                'price' => 1200000,
                'phone' => '0974671220',
                'email' => 'hunghoang_8xx@gmail.com',
                'description' => 'Dẫn tour Quy Nhơn. Tự lái xe riêng đưa đón (xe 9 chỗ). Có thể nói tiếng Anh',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 38,
                'account_id' => 42,
                'full_name' => 'Phạm Văn Cường',
                'age' => '27',
                'price' => 700000,
                'phone' => '0936.166.797',
                'email' => 'cuong_pham@gmail.com',
                'description' => 'Tour Tây Nguyên. Có thể dẫn tour bằng tiếng Anh',
                'thumbnail' => '',
                'area_id' => 41,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'account_id' => 43,
                'full_name' => 'Tống Mỹ Linh',
                'age' => '22',
                'price' => 1000000,
                'phone' => '0936255363',
                'email' => 'tong_mylinh@gmail.com',
                'description' => 'Dẫn tour bằng tiếng Việt, Trung, Anh, Hàn. Tour Tây Nguyên',
                'thumbnail' => '',
                'area_id' => 42,
                'card' => false,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 40,
                'account_id' => 44,
                'full_name' => 'Cao Việt Anh',
                'age' => '27',
                'price' => 700000,
                'phone' => '0353484548',
                'email' => 'vietanh_cao@gmail.com',
                'description' => 'Tour Tây Nguyên',
                'thumbnail' => '',
                'area_id' => 43,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 41,
                'account_id' => 45,
                'full_name' => 'Trần Đình Tuấn',
                'age' => '20',
                'price' => 500000,
                'phone' => '0379080070',
                'email' => 'dinhtuan_tran@gmail.com',
                'description' => 'Tour Tây Nguyên',
                'thumbnail' => '',
                'area_id' => 44,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 42,
                'account_id' => 46,
                'full_name' => 'Dương Quốc Thiên',
                'age' => '26',
                'price' => 1500000,
                'phone' => '0905473215',
                'email' => 'DuongThien3215@gmail.com',
                'description' => 'Thông thạo tiếng Trung,Anh và Hàn,có kinh nghiệm 5 năm dẫn đoàn tại khu vực Đà Nẵng',
                'thumbnail' => '',
                'area_id' => 33,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 43,
                'account_id' => 47,
                'full_name' => 'Nguyễn Trung Kiên',
                'age' => '23',
                'price' => 500000,
                'phone' => '0771268423',
                'email' => 'TKBaby72@gmail.com',
                'description' => 'Tự tin, thân thiện, vui vẻ.',
                'thumbnail' => '',
                'area_id' => 33,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 44,
                'account_id' => 48,
                'full_name' => 'Vũ Ngọc Minh',
                'age' => '31',
                'price' => 1000000,
                'phone' => '0979691998',
                'email' => 'Minhvu1989@gmail.com',
                'description' => 'Thân thiện, vui vẻ. Chuyên nhận dẫn tour khu vực Sapa',
                'thumbnail' => '',
                'area_id' => 13,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 45,
                'account_id' => 49,
                'full_name' => 'Võ Minh Hồng',
                'age' => '22',
                'price' => 1000000,
                'phone' => '0778531206',
                'email' => 'crybaby12@gmail.com',
                'description' => 'Tự tin, thân thiện, vui vẻ. Có thể dẫn tour bằng tiếng hàn và tiếng nhật',
                'thumbnail' => '',
                'area_id' => 46,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 46,
                'account_id' => 50,
                'full_name' => 'Võ Phạm Ngọc Giang',
                'age' => '25',
                'price' => 1200000,
                'phone' => '0979691520',
                'email' => 'Giangcutie@gmail.com',
                'description' => 'Thân thiện, thông thạo tiếng Đức. Có kinh nghiệm dẫn đoàn trong khu vực Cố đô Huế',
                'thumbnail' => '',
                'area_id' => 32,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 47,
                'account_id' => 51,
                'full_name' => 'Hoàng Quang Huy',
                'age' => '23',
                'price' => 1000000,
                'phone' => '0776280898',
                'email' => 'HuyHQ28@hotmail.com',
                'description' => 'Thân thiện, vui vẻ. Thông thạo tiếng anh và tiếng nhật',
                'thumbnail' => '',
                'area_id' => 51,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 48,
                'account_id' => 52,
                'full_name' => 'Mai Nam Anh',
                'age' => '27',
                'price' => 1500000,
                'phone' => '0125492386',
                'email' => 'maiquanghieu6998@gmail.com',
                'description' => 'Có kinh nghiệm 4 năm dẫn tour, thông thạo tiếng Ý và tiếng Anh',
                'thumbnail' => '',
                'area_id' => 13,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 49,
                'account_id' => 53,
                'full_name' => 'Hồ Thị Thu Thủy',
                'age' => '26',
                'price' => 1000000,
                'phone' => '0776283559',
                'email' => 'ThuyHT@gmail.com',
                'description' => 'Tự tin, thân thiện. Có thể dẫn tour bằng tiếng anh, chuyên nhân dẫn đoàn tại Đà lạt',
                'thumbnail' => '',
                'area_id' => 44,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 50,
                'account_id' => 54,
                'full_name' => 'Hồ Quang Hiếu',
                'age' => '25',
                'price' => 1300000,
                'phone' => '0975488288',
                'email' => 'HoHieu88@gmail.com',
                'description' => ' Có kinh nghiệm 3 năm dẫn tour tại khu vực Đồng tháp',
                'thumbnail' => '',
                'area_id' => 53,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 51,
                'account_id' => 55,
                'full_name' => 'Nguyễn Trà My',
                'age' => '23',
                'price' => 700000,
                'phone' => '0976861495',
                'email' => 'TraMyAngel@gmail.com',
                'description' => 'Tự tin, thân thiện. Nhận dẫn tour khu vực Hải Dương',
                'thumbnail' => '',
                'area_id' => 7,
                'card' => false,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => '',
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 52,
                'account_id' => 56,
                'full_name' => 'Nguyễn Hải Long',
                'age' => '25',
                'price' => 1000000,
                'phone' => '0975552908',
                'email' => 'nguyenhailong0812@gmail.com',
                'description' => 'Thân thiện, vui vẻ. Có thể dẫn tour bằng tiếng Pháp',
                'thumbnail' => '',
                'area_id' => 44,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 53,
                'account_id' => 57,
                'full_name' => 'Mai Ngọc Ánh',
                'age' => '22',
                'price' => 800000,
                'phone' => '0974152236',
                'email' => 'Ngocanh98@gmail.com',
                'description' => 'Tự tin, thân thiện, vui vẻ. Có thể dẫn tour bằng tiếng Anh',
                'thumbnail' => '',
                'area_id' => 32,
                'card' => false,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 54,
                'account_id' => 58,
                'full_name' => 'Nghiêm Thị Nga',
                'age' => '28',
                'price' => 1000000,
                'phone' => '0979652740',
                'email' => 'NTNga72@gmail.com',
                'description' => 'Thông thạo tiếng Đức và tiếng Nga, có kinh nghiệm dẫn tour tại khu vực Thanh Hóa',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 27,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 55,
                'account_id' => 59,
                'full_name' => 'Mai Hoàng Hiệp',
                'age' => '26',
                'price' => 1100000,
                'phone' => '0126682043',
                'email' => 'hoanghiep08@gmail.com',
                'description' => 'Thân thiện, có kinh nghiệm 3 năm dẫn tour tại khu vực HCM',
                'thumbnail' => '',
                'area_id' => 46,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 56,
                'account_id' => 60,
                'full_name' => 'Trương Thị Quỳnh Mai',
                'age' => '23',
                'price' => 800000,
                'phone' => '0776284115',
                'email' => 'BlueAngel115@gmail.com',
                'description' => 'Tự tin, thân thiện, vui vẻ. Có thể dẫn tour bằng tiếng Đức và tiếng Anh.',
                'thumbnail' => '',
                'area_id' => 46,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 57,
                'account_id' => 61,
                'full_name' => 'Nguyễn Ngọc Hà',
                'age' => '24',
                'price' => 500000,
                'phone' => '0776320198',
                'email' => 'Hacchama78@gmail.com',
                'description' => 'Thân thiện, vui vẻ. Có 1 năm kinh nghiệm dẫn tour khu vực Lăng chủ tịch HCM',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 58,
                'account_id' => 62,
                'full_name' => 'Lung Thị Linh',
                'age' => '30',
                'price' => 150000,
                'phone' => '09796531008',
                'email' => 'lunglinh90@gmail.com',
                'description' => 'Có Kinh nghiệm dẫn tour ở nhiều tỉnh thành như Đà Nẵng, Quảng Trị, Huế,....',
                'thumbnail' => '',
                'area_id' => 32,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 59,
                'account_id' => 63,
                'full_name' => 'Nguyễn Thành Nam',
                'age' => '27',
                'price' => 1000000,
                'phone' => '0971104623',
                'email' => 'NTN112@gmail.com',
                'description' => 'Tự tin, vui vẻ. Có thể dẫn tour bằng tiếng Anh và tiếng Nga',
                'thumbnail' => '',
                'area_id' => 38,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 60,
                'account_id' => 64,
                'full_name' => 'Đỗ Mai Linh',
                'age' => '24',
                'price' => 1000000,
                'phone' => '0124625529',
                'email' => 'Mailinh599@gmail.com',
                'description' => 'Thông thạo tiếng Anh, Pháp và Trung',
                'thumbnail' => '',
                'area_id' => 52,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],

            [
                'id' => 61,
                'account_id' => 65,
                'full_name' => 'Phan Thị Thu Hà',
                'age' => '24',
                'price' => 1200000,
                'phone' => '0121165487',
                'email' => 'thuhaofficial@hotmail.com',
                'description' => 'Thông thạo tiếng Anh, Trung. Có kinh nghiệm dẫn tour khu vực Quảng Ngãi',
                'thumbnail' => '',
                'area_id' => 35,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 62,
                'account_id' => 66,
                'full_name' => 'Nguyễn Minh Hải',
                'age' => '25',
                'price' => 1000000,
                'phone' => '0124625529',
                'email' => 'Haiquayxe@gmail.com',
                'description' => 'Thông thạo tiếng Pháp và Đức',
                'thumbnail' => '',
                'area_id' => 54,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 63,
                'account_id' => 67,
                'full_name' => 'Đặng Quang Chính',
                'age' => '24',
                'price' => 1000000,
                'phone' => '0912511440',
                'email' => 'chinhdangquang777@gmail.com',
                'description' => 'Năng nổ, hiểu biết nhiều về ẩm thực',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 64,
                'account_id' => 68,
                'full_name' => 'Phạm Quang Vinh',
                'age' => '27',
                'price' => 1500000,
                'phone' => '0124625529',
                'email' => 'Mailinh599@gmail.com',
                'description' => 'Thông thạo tiếng Anh, Nhật. Có kinh nghiệm dẫn tour khu vực Huế, Đà Nẵng',
                'thumbnail' => '',
                'area_id' => 32,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 65,
                'account_id' => 69,
                'full_name' => 'Dương Bình Minh',
                'age' => '25',
                'price' => 1000000,
                'phone' => '0774250989',
                'email' => 'binhminh1231@gmail.com',
                'description' => 'Thông thạo tiếng Pháp và Nhật',
                'thumbnail' => '',
                'area_id' => 46,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 66,
                'account_id' => 70,
                'full_name' => 'Phạm Quang Vinh',
                'age' => '28',
                'price' => 1200000,
                'phone' => '0145457829',
                'email' => 'Vinhcity@gmail.com',
                'description' => 'Thông thạo tiếng Anh. Có kinh nghiệm dẫn tour ở khu vực Hà Nội, Điện Biên, v,v...',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 67,
                'account_id' => 71,
                'full_name' => 'Đỗ Ngọc Anh',
                'age' => '23',
                'price' => 500000,
                'phone' => '0124625529',
                'email' => 'littleangel2212@gmail.com',
                'description' => 'Thông thạo tiếng Pháp',
                'thumbnail' => '',
                'area_id' => 55,
                'card' => false,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 68,
                'account_id' => 72,
                'full_name' => 'Lã Thị Thu Trang',
                'age' => '28',
                'price' => 1500000,
                'phone' => '0124625529',
                'email' => 'Mailinh599@gmail.com',
                'description' => 'Thông thạo tiếng Pháp. Đức, Ý. Có trên 4 năm kinh nghiệm dẫn tour tại khu vực Đà Nẵng.',
                'thumbnail' => '',
                'area_id' => 33,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 69,
                'account_id' => 73,
                'full_name' => 'Hoàng Quốc Việt',
                'age' => '29',
                'price' => 1300000,
                'phone' => '0125434529',
                'email' => 'vietpro12@gmail.com',
                'description' => 'Thông thạo tiếng Anh, Pháp và Trung. Có kinh nghiệm 5 năm dẫn tour tại khu vực HCM.',
                'thumbnail' => '',
                'area_id' => 46,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 70,
                'account_id' => 74,
                'full_name' => 'Đặng Cao Cường',
                'age' => '24',
                'price' => 1000000,
                'phone' => '0124625529',
                'email' => 'DCC555@gmail.com',
                'description' => 'Thông thạo tiếng Anh, Pháp và Nhật. Tour miền Tây',
                'thumbnail' => '',
                'area_id' => 58,
                'card' => true,
                'mc_gala_dinner' => true,
                'team_building' => true,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 71,
                'account_id' => 75,
                'full_name' => 'Đỗ Ngọc Linh',
                'age' => '23',
                'price' => 500000,
                'phone' => '0914527880',
                'email' => 'NgọcLinh1182@gmail.com',
                'description' => 'Thông thạo tiếng Trung. Tour miền Tây',
                'thumbnail' => '',
                'area_id' => 60,
                'card' => false,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 72,
                'account_id' => 76,
                'full_name' => 'Đặng Minh Thái',
                'age' => '24',
                'price' => 500000,
                'phone' => '0912511440',
                'email' => 'chinhdangquang777@gmail.com',
                'description' => 'Năng nổ, hiểu biết nhiều về ẩm thực. Dẫn tour người nước ngoài thăm quan phố ',
                'thumbnail' => '',
                'area_id' => 1,
                'card' => false,
                'mc_gala_dinner' => false,
                'team_building' => false,
                'start_time' => '',
                'end_time' => '',
                'status' => 1,
                'created_at' => Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->addDays(0)->format('Y-m-d H:i:s'),
            ],

        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');
    }
}
